version: '3.8'
services:
  auth-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '8888:3306'
    networks:
      - my_network

  resource-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: resource
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '9999:3306'
    networks:
      - my_network

  auth-server:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - '3002:3001'
      - '5001:5001'
    env_file:
      - .env
    environment:
      - DB_HOST=${AUTH_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${AUTH_DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_RESOURCE_SERVER_URL=${GRPC_AUTH_SERVER_URL}
    depends_on:
      - auth-db
    networks:
      - my_network

  resource-server:
    build:
      context: .
      dockerfile: ./apps/resource/Dockerfile
    ports:
      - '4002:4001'
    env_file:
      - .env
    environment:
      - DB_HOST=${RESOURCE_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${RESOURCE_DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_AUTH_SERVER_URL=${GRPC_AUTH_SERVER_URL}
    depends_on:
      - resource-db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
