name: Deploy to GCP

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때 워크플로가 실행되도록 설정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # auth 서비스 이미지 빌드 및 푸시
      - name: Build and push Docker image for auth service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/auth/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-auth:latest # auth 서비스 이미지 이름

      # resource 서비스 이미지 빌드 및 푸시
      - name: Build and push Docker image for resource service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/resource/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-resource:latest # resource 서비스 이미지 이름

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GCP VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.GCP_VM_IP }}
          REMOTE_USER: ${{ secrets.GCP_VM_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${REMOTE_HOST}" >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa "${REMOTE_USER}@${REMOTE_HOST}" << EOF
            cd nest-project
            docker-compose pull
            docker-compose restart
            exit
          EOF
